---
title: "Scratch Thought Regression"
author: "Dr. Williams"
date: "2/19/2022"
output: html_document
---
```{r}
library(MASS)
suppressPackageStartupMessages(library(tidyverse))
library(scales)
```


```{r}
sample_size_button = 100
correlation_button = 0.9
## 2) Generate Data
data = mvrnorm(n=sample_size_button, mu=c(0, 0), Sigma=matrix(c(1, 
                                                                correlation_button,
                                                                correlation_button,
                                                                1), 
                                                              nrow=2), 
               empirical=TRUE)

## 3) Turn Data into data frame
df = data.frame(X = data[, 1], Y = data[, 2] )

## 4) Plot Data

## 5) Run Model
slr_model = lm(Y ~ X, data = df)

summary(slr_model)


```



```{r}
## 6) Define expected response variable values, observed response variables, sample mean of the response variable
y_hat = predict(slr_model)
y_obs = df$Y
y_mean = mean(y_obs)


## 7) Define Sums of Square: Total, Error, & Treatment
SS_Total = sum((y_obs - y_mean)^2)
SS_Error = sum((y_obs - y_hat)^2)
SS_Treatment = sum((y_hat - y_mean)^2)


## 8) Define metrics - R-Square, Standard Deviation of Residuals
r_squared = SS_Treatment / SS_Total
s_e = sqrt( SS_Error / (sample_size_button - 2))


c(SS_Error,SS_Treatment)

```



```{r}
## 1) Create Data Frame for variability
 
condition <- factor(x = c("Explained","Unexplained"), 
                    levels = c("Unexplained","Explained")) 
value <- c(SS_Treatment,SS_Error)
percent_var <- c(SS_Treatment/SS_Total,SS_Error/SS_Total)
var_df <- data.frame(condition,value,percent_var)


## Create plot based on variability Explained
var_df %>% 
  ggplot( aes( x = 1, y=percent_var, fill=condition)) + 
  geom_bar( stat="identity") +
  
  scale_fill_manual(values=c("#999999", "#E69F00")) +
  labs(y = 'Total Variability',fill = 'Type of Variability' ) +
  theme_bw() +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  coord_flip() 


```


